config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'homes/top'
  end
  namespace :admin do
    get 'relationships/followings'
    get 'relationships/followers'
  end
  root to: 'public/homes#top'

  scope module: :public do
    get 'timeline', to: 'posts#timeline'
    get 'posts/drafts'
    get 'posts/draft/:id/edit', to: 'posts#edit_draft', as: 'edit_post_draft'
    get 'posts/draft/:id', to: 'posts#show_draft', as: 'post_draft'
    patch 'posts/draft/:id', to: 'posts#update_draft'
    resources :posts, except: [:new] do
      post 'favorite', to: 'post_favorites#create'
      delete 'favorite', to: 'post_favorites#destroy'
      get 'update_history'
    end

    get 'search', to: 'searches#search'

    resources :comments, only: [:show, :create, :edit, :update, :destroy] do
      post 'favorite', to: 'comment_favorites#create'
      delete 'favorite', to: 'comment_favorites#destroy'
      get 'update_history'
    end

    resources :direct_messages, only: [:index, :show, :create]

    scope '/:account_id' do
      get 'edit', to: 'users#edit', as: 'edit_user'
      get '', to: 'users#show', as: 'user'
      patch '', to: 'users#update', as: 'user_patch', param: :account_id
      put '', to: 'users#update', as: 'user_put', param: :account_id
      delete '', to: 'users#destroy', as: 'user_delete', param: :account_id
      resource :relationships, only: [:create, :destroy]
      get 'followings', to: 'relationships#followings'
      get 'followers', to: 'relationships#followers'
    end
  end

  namespace :admin do
    resources :posts, only: [:index, :show, :update] do
      get 'update_history'
    end
    resources :users, only: [:index]
    resources :comments, only: [:index, :show, :update]
    get 'search', to: 'searches#search'

    scope '/:account_id' do
      get 'edit', to: 'users#edit', as: 'edit_user'
      get '', to: 'users#show', as: 'user'
      patch '', to: 'users#update', as: 'user_patch'
      put '', to: 'users#update', as: 'user_put'
      get 'followings', to: 'relationships#followings'
      get 'followers', to: 'relationships#followers'
    end
  end

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admins,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :comment_favorites, dependent: :destroy
  has_many :comment_histories, dependent: :destroy

  belongs_to :user
  belongs_to :post

  def status
    if is_hidden
      "非公開"
    else
      "公開"
    end
  end

  def favorited_by?(user)
    comment_favorites.exists?(user_id: user.id)
  end
end

app/models/comment_favorite.rb
class CommentFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/comment_history.rb
class CommentHistory < ApplicationRecord
  belongs_to :comment
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :direct_messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :direct_messages
end

app/models/post.rb
class Post < ApplicationRecord
  before_save :set_published_at

  validates :body, presence: true, length: {in: 1..1000}

  has_many :comments
  has_many :post_favorites, dependent: :destroy
  has_many :post_histories, dependent: :destroy

  belongs_to :user

  def status
    if is_hidden
      "非公開"
    else
      "公開"
    end
  end

  def favorited_by?(user)
    post_favorites.exists?(user_id: user.id)
  end

  def set_published_at
    if is_draft == false && published_at.nil?
      self.published_at = Time.zone.now
    elsif is_draft_changed? && is_draft == false
      self.published_at = Time.current
    end
  end

  def self.search_for_post(word, search)
    if search == "partial_match"
      Post.where("body LIKE?", "%#{word}%")
    elsif search == "forward_match"
      Post.where("body LIKE?", "#{word}%")
    elsif search == "backward_match"
      Post.where("body LIKE?", "%#{word}")
    elsif search == "perfect_match"
      Post.where("body LIKE?", "#{word}")
    else
      Post.all
    end
  end

end

app/models/post_favorite.rb
class PostFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/post_history.rb
class PostHistory < ApplicationRecord
  belongs_to :post
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # 半角英数字のみ受け付ける正規表現
  VALID_ACCOUNT_NAME_REGEX = /\A[A-Za-z0-9_]+\z/

  validates :name, presence: true, length: {in: 1..50}
  validates :introduction, length: { maximum: 200 }
  validates :account_id, presence: true,
                         uniqueness: true,
                         length: {in: 5..15},
                         format: { with: VALID_ACCOUNT_NAME_REGEX, message: "英数字と_のみ使用可能です" }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_favorites, dependent: :destroy
  has_many :comment_favorites, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  # フォロー・フォロワー　リレーション
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def status
    if is_active
      "有効"
    else
      "停止"
    end
  end

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for_name(word, search)
    if search == "partial_match"
      User.where("name LIKE?", "%#{word}%")
    elsif search == "forward_match"
      User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      User.where("name LIKE?", "%#{word}")
    elsif search == "perfect_match"
      User.where("name LIKE?", "#{word}")
    else
      User.all
    end
  end

  def self.search_for_account_id(word, search)
    if search == "partial_match"
      User.where("account_id LIKE?", "%#{word}%")
    elsif search == "forward_match"
      User.where("account_id LIKE?", "#{word}%")
    elsif search == "backward_match"
      User.where("account_id LIKE?", "%#{word}")
    elsif search == "perfect_match"
      User.where("account_id LIKE?", "#{word}")
    else
      User.all
    end
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      user.account_id = SecureRandom.base36(15)
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/conversations/_comment_items.html.erb
<% comment_items.each do |comment_item| %>
  <div class="post-row user-post-row">
    <div class="user-name">
      <span class="text-title">ユーザー名: </span>
        <%= link_to user_path(comment_item.user.account_id), class: "content-link-black" do %>
          <span><strong><%= comment_item.user.name %></strong></span>
        <% end %>
    </div>
    <div class="user-name">
      <span class="text-title">アカウントID: </span>
      <span><%= comment_item.user.account_id %></span>
    </div>
    <div>
      <span class="text-title">投稿内容:</span><br>
      <%= link_to admin_comment_path(comment_item.id), class: "content-link-black post-text-link" do %>
        <%= safe_join(comment_item.body.split("\n").map { |line| h(line) }, tag(:br)) %>
      <% end %>
    </div>
    <div>
      <%= render "admin/favorites/comment", comment: comment_item %>
    </div>
    <div>
      <span class="text-title">投稿日時:</span>
      <span class="history-datetime"><%= time_ago_in_words(comment_item.created_at) %>前</span>
    </div>
    <div>
      <% if comment_item.comment_histories.present? %>
        <span class="text-title">最終更新日時:</span>
        <%= link_to post_update_history_path(comment_item.id), class: "history-link content-link-black" do %>
          <span class="history-datetime"><strong><%= l comment_item.updated_at, format: :long %></strong></span>
        <% end %>
      <% end %>
    </div>
    <div>
      <span class="text-title">ステータス: </span>
      <% if comment_item.is_hidden %>
        <span class="user-inactive"><strong><%= comment_item.status %></strong></span>
      <% else %>
        <span class="user-active"><strong><%= comment_item.status %></strong></span>
      <% end %>
    </div>
  </div>
<% end %>
<%= paginate comment_items %>

app/views/admin/conversations/_comment_show.html.erb
<div class="post-row">
  <div class="user-name">
    <span class="text-title">ユーザー名: </span>
    <%= link_to user_path(comment.user.account_id), class: "content-link-black" do %>
      <span><strong><%= comment.user.name %></strong></span>
    <% end %>
  </div>
  <div class="user-name">
    <span class="text-title">アカウントID: </span>
    <span><%= comment.user.account_id %></span>
  </div>
  <div>
    <span class="text-title">投稿内容:</span><br>
    <%= content_tag :div, class: "content-link-black post-text" do %>
      <%= safe_join(comment.body.split("\n").map { |line| h(line) }, tag(:br)) %>
    <% end %>
  </div>
  <div>
    <%= render "admin/favorites/comment", comment: comment %>
  </div>
  <div>
    <span class="text-title">投稿日時:</span>
    <span class="history-datetime"><%= l comment.created_at, format: :long %></span>
  </div>
  <div class="post-history-content">
    <% if comment.comment_histories.present? %>
      <span class="text-title">最終更新日時:</span>
      <%= link_to comment_update_history_path(comment.id), class: "history-link content-link-black" do %>
        <span class="history-datetime"><strong><%= l comment.updated_at, format: :long %></strong></span>
      <% end %>
    <% end %>
  </div>
  <div>
    <span class="text-title">ステータス: </span>
    <% if comment.is_hidden %>
      <span class="user-inactive"><strong><%= comment.status %></strong></span>
    <% else %>
      <span class="user-active"><strong><%= comment.status %></strong></span>
    <% end %>
  </div>
  <%= form_with model: comment, url: admin_comment_path(comment.id), data: {confirm: "スタータスを変更しますか？"}, method: :patch do |f| %>
    <div class="acction-bottons">
      <div class="checkbox-content is-draft-checkbox-content">
        <%= f.check_box :is_hidden %>
        <%= f.label :is_hidden, class: "checkbox-label is-draft-label" do %>
          <span><strong>非公開にする</strong></span>
        <% end %>
      </div>
      <div class="submit-btn post-submit">
        <%= f.submit "編集する", class: "post-submit" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/conversations/_post_items.html.erb
<% post_items.each do |post_item| %>
  <div class="post-row user-post-row">
    <div class="user-name">
      <span class="text-title">ユーザー名: </span>
        <%= link_to admin_user_path(post_item.user.account_id), class: "content-link-black" do %>
          <span><strong><%= post_item.user.name %></strong></span>
        <% end %>
    </div>
    <div class="user-name">
      <span class="text-title">アカウントID: </span>
      <span><%= post_item.user.account_id %></span>
    </div>
    <div>
      <span class="text-title">投稿内容:</span><br>
      <%= link_to admin_post_path(post_item.id), class: "content-link-black post-text-link" do %>
        <%= safe_join(post_item.body.split("\n").map { |line| h(line) }, tag(:br)) %>
      <% end %>
    </div>
    <div>
      <%= render "admin/favorites/post", post: post_item %>
    </div>
    <div>
      <span class="text-title">投稿日時:</span>
      <span class="history-datetime"><%= time_ago_in_words(post_item.published_at) %>前</span>
    </div>
    <div>
      <% if post_item.post_histories.present? %>
        <span class="text-title">最終更新日時:</span>
        <%= link_to admin_post_update_history_path(post_item.id), class: "history-link content-link-black" do %>
          <span class="history-datetime"><strong><%= l post_item.updated_at, format: :long %></strong></span>
        <% end %>
      <% end %>
    </div>
    <div>
      <span class="text-title">ステータス: </span>
      <% if post_item.is_hidden %>
        <span class="user-inactive"><strong><%= post_item.status %></strong></span>
      <% else %>
        <span class="user-active"><strong><%= post_item.status %></strong></span>
      <% end %>
    </div>
  </div>
<% end %>
<%= paginate post_items %>

app/views/admin/conversations/_post_show.html.erb
<div class="post-row">
  <div class="user-name">
    <span class="text-title">ユーザー名: </span>
    <%= link_to admin_user_path(post.user.account_id), class: "content-link-black" do %>
      <span><strong><%= post.user.name %></strong></span>
    <% end %>
  </div>
  <div class="user-name">
    <span class="text-title">アカウントID: </span>
    <span><%= post.user.account_id %></span>
  </div>
  <div>
    <span class="text-title">投稿内容:</span><br>
    <%= content_tag :div, class: "post-text" do %>
      <%= safe_join(post.body.split("\n").map { |line| h(line) }, tag(:br)) %>
    <% end %>
  </div>
  <div>
    <%= render "admin/favorites/post", post: post %>
  </div>
  <div>
    <span class="text-title">投稿日時:</span>
    <span class="history-datetime"><%= l post.published_at, format: :long %></span>
  </div>
  <div class="post-history-content">
    <% if post.post_histories.present? %>
      <span class="text-title">最終更新日時:</span>
      <%= link_to admin_post_update_history_path(post.id), class: "history-link content-link-black" do %>
        <span class="history-datetime"><strong><%= l post.updated_at, format: :long %></strong></span>
      <% end %>
    <% end %>
  </div>
  <div>
    <span class="text-title">ステータス: </span>
    <% if post.is_hidden %>
      <span class="user-inactive"><strong><%= post.status %></strong></span>
    <% else %>
      <span class="user-active"><strong><%= post.status %></strong></span>
    <% end %>
  </div>
  <%= form_with model: post, url: admin_post_path(post.id), data: {confirm: "スタータスを変更しますか？"}, method: :patch do |f| %>
    <div class="acction-bottons">
      <div class="checkbox-content is-draft-checkbox-content">
        <%= f.check_box :is_hidden %>
        <%= f.label :is_hidden, class: "checkbox-label is-draft-label" do %>
          <span><strong>非公開にする</strong></span>
        <% end %>
      </div>
      <div class="submit-btn post-submit">
        <%= f.submit "編集する", class: "post-submit" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/favorites/_comment.html.erb
<div class="favorite-link admin-favorite">
  <i class="fa-solid fa-heart favorite-icon"></i>
  <span class="favorite-count"><%= comment.comment_favorites.count %> いいね</span>
</div>

app/views/admin/favorites/_post.html.erb
<div class="favorite-link admin-favorite">
  <i class="fa-solid fa-heart favorite-icon"></i>
  <span class="favorite-count"><%= post.post_favorites.count %> いいね</span>
</div>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer></footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="header-items">
    <h2><%= link_to "つなゲ～ム", root_path, class: "header-logo" %></h2>
    <%= link_to "ログイン", new_user_session_path, class: "header-item" %>
    <%= link_to "新規登録", new_user_registration_path, class: "header-item" %>
    <%= link_to "ゲストログイン(閲覧のみ)", users_guest_sign_in_path, class: "header-item", method: :post %>
  </nav>
</header>

app/views/layouts/_header_admin.html.erb
<header>
  <nav class="header-items">
    <h2><%= link_to "つなゲ～ム", root_path, class: "header-logo" %></h2>
    <%= link_to "ユーザー一覧", admin_users_path, class: "header-item nav-timeline" %>
    <%= link_to "投稿一覧", admin_posts_path, class: "header-item nav-posts" %>
    <%= link_to "コメント一覧", admin_comments_path, class: "header-item nav-search" %>
    <div id="hm-icon">
      <%= link_to "#", class: "menu-trigger" do %>
        <span></span>
        <span></span>
        <span></span>
      <% end %>
    </div>
  </nav>
  <nav class="admin-sp-menu" id="sp-menu">
    <ul>
      <%= link_to admin_search_path do %>
        <li>検索</li>
      <% end %>
      <%= link_to destroy_admin_session_path, method: :delete do %>
        <li>ログアウト</li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_header_user.html.erb
<header>
  <nav class="header-items">
    <h2><%= link_to "つなゲ～ム", root_path, class: "header-logo" %></h2>
    <%= link_to "タイムライン", timeline_path, class: "header-item nav-timeline" %>
    <%= link_to "最新投稿", posts_path, class: "header-item nav-posts" %>
    <%= link_to "検索", search_path, class: "header-item nav-search" %>
    <span>ユーザー名:<%= current_user.name %></span>
    <div id="hm-icon">
      <%= link_to "#", class: "menu-trigger" do %>
        <span></span>
        <span></span>
        <span></span>
      <% end %>
    </div>
  </nav>
  <nav class="user-sp-menu" id="sp-menu">
    <ul>
      <%= link_to user_path(current_user.account_id) do %>
        <li>マイページ</li>
      <% end %>
      <%= link_to posts_drafts_path do %>
        <li>下書き</li>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete do %>
        <li>ログアウト</li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title class="jquery">つなゲ～ム</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/9cef0bc0f1.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- ログイン状況に応じたヘッダーを表示 -->
    <% if user_signed_in? %>
      <%= render "layouts/header_user" %>
    <% elsif admin_signed_in? %>
      <%= render "layouts/header_admin" %>
    <% else %>
      <%= render "layouts/header" %>
    <% end %>
    <!-- フラッシュメッセージ -->
    <% flash.each do |message_type, message| %>
      <div class="flash-message flash-message-<%= message_type %>"><%= message %></div>
    <% end %>
    <main>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>