config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'homes/top'
  end
  namespace :admin do
    get 'relationships/followings'
    get 'relationships/followers'
  end
  root to: 'public/homes#top'

  scope module: :public do
    get 'timeline', to: 'posts#timeline'
    get 'posts/drafts'
    get 'posts/draft/:id/edit', to: 'posts#edit_draft', as: 'edit_post_draft'
    get 'posts/draft/:id', to: 'posts#show_draft', as: 'post_draft'
    patch 'posts/draft/:id', to: 'posts#update_draft'
    resources :posts, except: [:new] do
      post 'favorite', to: 'post_favorites#create'
      delete 'favorite', to: 'post_favorites#destroy'
      get 'update_history'
    end

    get 'search', to: 'searches#search'

    resources :comments, only: [:show, :create, :edit, :update, :destroy] do
      post 'favorite', to: 'comment_favorites#create'
      delete 'favorite', to: 'comment_favorites#destroy'
      get 'update_history'
    end

    resources :direct_messages, only: [:index, :show, :create]

    scope '/:account_id' do
      get 'edit', to: 'users#edit', as: 'edit_user'
      get '', to: 'users#show', as: 'user'
      patch '', to: 'users#update', as: 'user_patch', param: :account_id
      put '', to: 'users#update', as: 'user_put', param: :account_id
      delete '', to: 'users#destroy', as: 'user_delete', param: :account_id
      resource :relationships, only: [:create, :destroy]
      get 'followings', to: 'relationships#followings'
      get 'followers', to: 'relationships#followers'
    end
  end

  namespace :admin do
    resources :posts, only: [:index, :show, :update] do
      get 'update_history'
    end
    resources :users, only: [:index]
    resources :comments, only: [:index, :show, :update]
    get 'search', to: 'searches#search'

    scope '/:account_id' do
      get 'edit', to: 'users#edit', as: 'edit_user'
      get '', to: 'users#show', as: 'user'
      patch '', to: 'users#update', as: 'user_patch'
      put '', to: 'users#update', as: 'user_put'
      get 'followings', to: 'relationships#followings'
      get 'followers', to: 'relationships#followers'
    end
  end

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admins,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # 半角英数字のみ受け付ける正規表現
  VALID_ACCOUNT_NAME_REGEX = /\A[A-Za-z0-9_]+\z/

  validates :name, presence: true, length: {in: 1..50}
  validates :introduction, length: { maximum: 200 }
  validates :account_id, presence: true,
                         uniqueness: true,
                         length: {in: 5..15},
                         format: { with: VALID_ACCOUNT_NAME_REGEX, message: "英数字と_のみ使用可能です" }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_favorites, dependent: :destroy
  has_many :comment_favorites, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  # フォロー・フォロワー　リレーション
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def status
    if is_active
      "有効"
    else
      "停止"
    end
  end

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for_name(word, search)
    if search == "partial_match"
      User.where("name LIKE?", "%#{word}%")
    elsif search == "forward_match"
      User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      User.where("name LIKE?", "%#{word}")
    elsif search == "perfect_match"
      User.where("name LIKE?", "#{word}")
    else
      User.all
    end
  end

  def self.search_for_account_id(word, search)
    if search == "partial_match"
      User.where("account_id LIKE?", "%#{word}%")
    elsif search == "forward_match"
      User.where("account_id LIKE?", "#{word}%")
    elsif search == "backward_match"
      User.where("account_id LIKE?", "%#{word}")
    elsif search == "perfect_match"
      User.where("account_id LIKE?", "#{word}")
    else
      User.all
    end
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      user.account_id = SecureRandom.base36(15)
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.where.not(name: "guestuser").order(created_at: :desc).page(params[:page])
  end

  def show
    @user = User.find_by(account_id: params[:account_id])
    @user_posts = @user.posts.where(is_draft: false).order(published_at: :desc).page(params[:page])
    @user_comments = @user.comments.order(created_at: :desc).page(params[:page])

    @favorite_posts = PostFavorite.where(user_id: @user.id).order(created_at: :desc).map(&:post).select { |post| post.is_hidden == false }
    @favorite_posts = Kaminari.paginate_array(@favorite_posts).page(params[:page])

    @favorite_comments = CommentFavorite.where(user_id: @user.id).order(created_at: :desc).map(&:comment).select { |comment| comment.is_hidden == false }
    @favorite_comments = Kaminari.paginate_array(@favorite_comments).page(params[:page])

    @followings = @user.followings
    @follower_users = @user.followers
  end

  def edit

  end

  def update
    @user = User.find_by(account_id: params[:account_id])
    if @user.update(user_params)
      flash[:notice] = "編集に成功しました。"
      redirect_to admin_user_path(@user.account_id)
    else
      flash.now[:alert] = "編集に失敗しました。"
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(:is_active)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_user_index.html.erb
<% users.each do |user| %>
  <div class="post-row user-post-row">
    <div class="user-name">
      <%= link_to admin_user_path(user.account_id), class: "content-link-black content-link-hover-black" do %>
        <span class="text-title">ユーザー名: </span>
        <span><strong><%= user.name %></strong></span>
      <% end %>
    </div>
    <div class="user_name">
      <span class="text-title">アカウントID: </span>
      <span><%= user.account_id %></span>
    </div>
    <div>
      <span class="text-title">紹介文:</span><br>
      <% if user.introduction.present? %>
        <%= content_tag :div, class: "content-link-black post-text" do %>
          <%= safe_join(user.introduction.split("\n").map { |line| h(line) }, tag(:br)) %>
        <% end %>
      <% end %>
    </div>
    <div>
      <div>
        <%= link_to admin_followings_path(user.account_id), class: "text-title-link content-link-black content-link-hover-black" do %>
          <span class="text-title">フォロー中: </span>
          <span><strong><%= user.followings.where(is_active: true).count %></strong></span>
        <% end %>
      </div>
      <div>
        <%= link_to admin_followers_path(user.account_id), class: "text-title-link content-link-black content-link-hover-black" do %>
          <span class="text-title">フォロワー: </span>
          <span><strong><%= user.followers.where(is_active: true).count %></strong></span>
        <% end %>
      </div>
      <div>
        <span class="text-title">ステータス: </span>
        <% if user.is_active %>
          <span class="user-active"><strong><%= user.status %></strong></span>
        <% else %>
          <span class="user-inactive"><strong><%= user.status %></strong></span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<%= paginate users %>

app/views/admin/users/index.html.erb
<div class="container main-content-container">
  <div class="row main-content-row">
    <div class="main-content-col main-col-center">
      <h3 class="text-heading">～ユーザー一覧～</h3>
      <%= render "admin/users/user_index", users: @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container main-content-container">
  <div class="row main-content-row">
    <!--メイン左側-->
    <div class="main-content-col main-col-side">
      <h3 class="text-heading">～ユーザー詳細～</h3>
      <div class="post-row">
        <div class="user-name">
          <span class="text-title">ユーザー名: </span>
          <span><%= @user.name %></span>
        </div>
        <div class="user-name">
          <span class="text-title">アカウントID: </span>
          <span><%= @user.account_id %></span>
        </div>
        <div>
          <span class="text-title">紹介文:</span><br>
          <% if @user.introduction.present? %>
            <%= content_tag :div, class: "content-link-black post-text" do %>
              <%= safe_join(@user.introduction.split("\n").map { |line| h(line) }, tag(:br)) %>
            <% end %>
          <% end %>
        </div>
        <div>
          <div>
            <%= link_to admin_followings_path(@user.account_id), class: "text-title-link content-link-black content-link-hover-black" do %>
              <span class="text-title">フォロー中: </span>
              <span><strong><%= @user.followings.where(is_active: true).count %></strong></span>
            <% end %>
          </div>
          <div>
            <%= link_to admin_followers_path(@user.account_id), class: "text-title-link content-link-black content-link-hover-black" do %>
              <span class="text-title">フォロワー: </span>
              <span><strong><%= @user.followers.where(is_active: true).count %></strong></span>
            <% end %>
          </div>
        </div>
        <div>
          <span class="text-title">ステータス: </span>
          <% if @user.is_active %>
            <span class="user-active"><strong><%= @user.status %></strong></span>
          <% else %>
            <span class="user-inactive"><strong><%= @user.status %></strong></span>
          <% end %>
        </div>
        <div>
          <%= form_with model: @user, url: admin_user_patch_path, data: {confirm: "スタータスを変更しますか？"} do |f| %>
            <div class="acction-bottons">
              <div class="checkbox-content is-draft-checkbox-content">
                <%= f.check_box :is_active %>
                <%= f.label :is_active, class: "checkbox-label is-draft-label" do %>
                  <span><strong>公開にする</strong></span>
                <% end %>
              </div>
              <div class="submit-btn post-submit">
                <%= f.submit "編集する", class: "post-submit" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <!--メイン中央-->
    <div class="main-content-col main-col-center">
      <h3 class="main-h3"><%= @user.name %>の投稿一覧・いいね一覧</h3>
      <!--選択タブ-->
      <div class="post-favorite-tabs">
        <div class="user-tab tab-active">
          <span>投稿一覧</span>
        </div>
        <div class="user-tab">
          <span>コメント一覧</span>
        </div>
        <div class="user-tab">
          <span>投稿いいね一覧</span>
        </div>
        <div class="user-tab">
          <span>コメントいいね一覧</span>
        </div>
      </div>
      <!--タブで選択した要素-->
      <div class="tabbox-contents">
        <div class="tabbox box-show">
          <%= render "admin/conversations/post_items", post_items: @user_posts %>
        </div>
        <div class="tabbox">
          <%= render "admin/conversations/comment_items", comment_items: @user_comments %>
        </div>
        <div class="tabbox">
          <%= render "admin/conversations/post_items", post_items: @favorite_posts %>
        </div>
        <div class="tabbox">
          <%= render "admin/conversations/comment_items", comment_items: @favorite_comments %>
        </div>
      </div>
    </div>
    <!--メイン右側-->
    <div class="main-content-col main-col-side">
      <h3 class="main-h3">投稿詳細</h3>
      <p>部分テンプレート</p>
      <p>wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</p>
    </div>
  </div>
</div>